export type TimezoneName = {
  "name": string,
  "nameCn": string,
  "value": string,
  "utcOffset": string,
  "timezoneName": string,
}

export const timezoneNames: TimezoneName[] = [
  {
    "name": "(UTC+08:00) Beijing, Chongqing, Hong Kong, Urumqi",
    "nameCn": "(UTC+08:00) 北京，重庆，香港特别行政区，乌鲁木齐",
    "value": "China Standard Time",
    "utcOffset": "+08:00",
    "timezoneName": "PRC",
  },
  {
    "name": "(UTC-08:00) Pacific Time (US & Canada)",
    "nameCn": "(UTC-08:00) 太平洋时间(美国和加拿大)",
    "value": "Pacific Standard Time",
    "utcOffset": "-08:00",
    "timezoneName": "Pacific/Pitcairn",
  },
  {
    "name": "(UTC-07:00) Mountain Time (US & Canada)",
    "nameCn": "(UTC-07:00) 山地时间(美国和加拿大)",
    "value": "Mountain Standard Time",
    "utcOffset": "-07:00",
    "timezoneName": "US/Mountain",
  },
  {
    "name": "(UTC-06:00) Central Time (US & Canada)",
    "nameCn": "(UTC-06:00) 中部时间(美国和加拿大)",
    "value": "Central Standard Time",
    "utcOffset": "-06:00",
    "timezoneName": "US/Central",
  },
  {
    "name": "(UTC+00:00) Dublin, Edinburgh, Lisbon, London",
    "nameCn": "(UTC+00:00) 都柏林，爱丁堡，里斯本，伦敦",
    "value": "GMT Standard Time",
    "utcOffset": "+00:00",
    "timezoneName": "GMT",
  },
  {
    "name": "(UTC) Coordinated Universal Time",
    "nameCn": "(UTC) 协调世界时",
    "value": "UTC",
    "utcOffset": "+00:00",
    "timezoneName": "UTC",
  },
  {
    "name": "(UTC+01:00) Amsterdam, Berlin, Bern, Rome, Stockholm, Vienna",
    "nameCn": "(UTC+01:00) 阿姆斯特丹，柏林，伯尔尼，罗马，斯德哥尔摩，维也纳",
    "value": "W. Europe Standard Time",
    "utcOffset": "+01:00",
    "timezoneName": "Europe/Paris",
  },
  {
    "name": "(UTC+05:30) Chennai, Kolkata, Mumbai, New Delhi",
    "nameCn": "(UTC+05:30) 钦奈，加尔各答，孟买，新德里",
    "value": "India Standard Time",
    "utcOffset": "+05:30",
    "timezoneName": "Asia/Kolkata",
  },
  {
    "name": "(UTC+09:00) Osaka, Sapporo, Tokyo",
    "nameCn": "(UTC+09:00) 大阪，札幌，东京",
    "value": "Tokyo Standard Time",
    "utcOffset": "+09:00",
    "timezoneName": "Asia/Tokyo",
  },
  {
    "name": "(UTC+10:00) Canberra, Melbourne, Sydney",
    "nameCn": "(UTC+10:00) 堪培拉，墨尔本，悉尼",
    "value": "AUS Eastern Standard Time",
    "utcOffset": "+10:00",
    "timezoneName": "Australia/Sydney",
  },
  //
  // {
  //   "name": "(UTC-12:00) International Date Line West",
  //   "nameCn": "(UTC-12:00) 国际日期变更线西",
  //   "value": "Dateline Standard Time",
  //   "utcOffset": "-12:00",
  //   "timezoneName": "Etc/GMT+12",
  // },
  // {
  //   "name": "(UTC+13:00) Samoa",
  //   "nameCn": "(UTC+13:00) 萨摩亚",
  //   "value": "Samoa Standard Time",
  //   "utcOffset": "+13:00",
  //   "timezoneName": "Etc/GMT-13",
  // },
  // {
  //   "name": "(UTC-11:00) Coordinated Universal Time-11",
  //   "nameCn": "(UTC-11:00) 协调世界时-11",
  //   "value": "UTC-11",
  //   "utcOffset": "-11:00",
  //   "timezoneName": "Etc/GMT+11",
  // },
  // {
  //   "name": "(UTC-10:00) Aleutian Islands",
  //   "nameCn": "(UTC-10:00) 阿留申群岛",
  //   "value": "Aleutian Standard Time",
  //   "utcOffset": "-10:00",
  //   "timezoneName": "Etc/GMT+10",
  // },
  // {
  //   "name": "(UTC-10:00) Hawaii",
  //   "nameCn": "(UTC-10:00) 夏威夷",
  //   "value": "Hawaiian Standard Time",
  //   "utcOffset": "-10:00",
  //   "timezoneName": "Etc/GMT+10",
  // },
  // // {
  // //   "name": "(UTC-09:30) Marquesas Islands",
  // //   "nameCn": "(UTC-09:30) 马克萨斯群岛",
  // //   "value": "Marquesas Standard Time",
  // //   "utcOffset": "-09:30",
  // //   "timezoneName": "Etc/GMT+9",
  // // },
  // {
  //   "name": "(UTC-09:00) Alaska",
  //   "nameCn": "(UTC-09:00) 阿拉斯加",
  //   "value": "Alaskan Standard Time",
  //   "utcOffset": "-09:00",
  //   "timezoneName": "Etc/GMT+9",
  // },
  // {
  //   "name": "(UTC-09:00) Coordinated Universal Time-09",
  //   "nameCn": "(UTC-09:00) 协调世界时-09",
  //   "value": "UTC-09",
  //   "utcOffset": "-09:00",
  //   "timezoneName": "Etc/GMT+9",
  // },
  // {
  //   "name": "(UTC-08:00) Baja California",
  //   "nameCn": "(UTC-08:00) 下加利福尼亚",
  //   "value": "Pacific Standard Time (Mexico)",
  //   "utcOffset": "-08:00",
  //   "timezoneName": "Etc/GMT+8",
  // },
  // {
  //   "name": "(UTC-08:00) Coordinated Universal Time-08",
  //   "nameCn": "(UTC-08:00) 协调世界时-08",
  //   "value": "UTC-08",
  //   "utcOffset": "-08:00",
  //   "timezoneName": "Etc/GMT+8",
  // },
  // {
  //   "name": "(UTC-07:00) Arizona",
  //   "nameCn": "(UTC-07:00) 亚利桑那",
  //   "value": "US Mountain Standard Time",
  //   "utcOffset": "-07:00",
  //   "timezoneName": "Etc/GMT+7",
  // },
  // {
  //   "name": "(UTC-07:00) Chihuahua, La Paz, Mazatlan",
  //   "nameCn": "(UTC-07:00) 奇瓦瓦，拉巴斯，马扎特兰",
  //   "value": "Mountain Standard Time (Mexico)",
  //   "utcOffset": "-07:00",
  //   "timezoneName": "Etc/GMT+7",
  // },
  // {
  //   "name": "(UTC-05:00) Chetumal",
  //   "nameCn": "(UTC-05:00) 切图马尔",
  //   "value": "Eastern Standard Time (Mexico)",
  //   "utcOffset": "-05:00",
  //   "timezoneName": "Etc/GMT+5",
  // },
  // {
  //   "name": "(UTC-06:00) Central America",
  //   "nameCn": "(UTC-06:00) 中美洲",
  //   "value": "Central America Standard Time",
  //   "utcOffset": "-06:00",
  //   "timezoneName": "Etc/GMT+6",
  // },
  // {
  //   "name": "(UTC-06:00) Easter Island",
  //   "nameCn": "(UTC 06:00) 复活岛",
  //   "value": "Easter Island Standard Time",
  //   "utcOffset": "-06:00",
  //   "timezoneName": "Etc/GMT+6",
  // },
  // {
  //   "name": "(UTC-06:00) Guadalajara, Mexico City, Monterrey",
  //   "nameCn": "(UTC-06:00) 瓜达拉哈拉，墨西哥城，蒙特雷",
  //   "value": "Central Standard Time (Mexico)",
  //   "utcOffset": "-06:00",
  //   "timezoneName": "Etc/GMT+6",
  // },
  // {
  //   "name": "(UTC-06:00) Saskatchewan",
  //   "nameCn": "(UTC-06:00) 萨斯喀彻温",
  //   "value": "Canada Central Standard Time",
  //   "utcOffset": "-06:00",
  //   "timezoneName": "Etc/GMT+6",
  // },
  // {
  //   "name": "(UTC-05:00) Bogota, Lima, Quito, Rio Branco",
  //   "nameCn": "(UTC-05:00) 波哥大，利马，基多，里奥布郎库",
  //   "value": "SA Pacific Standard Time",
  //   "utcOffset": "-05:00",
  //   "timezoneName": "Etc/GMT+5",
  // },
  // {
  //   "name": "(UTC-05:00) Eastern Time (US & Canada)",
  //   "nameCn": "(UTC-05:00) 东部时间(美国和加拿大)",
  //   "value": "Eastern Standard Time",
  //   "utcOffset": "-05:00",
  //   "timezoneName": "Etc/GMT+5",
  // },
  // {
  //   "name": "(UTC-05:00) Haiti",
  //   "nameCn": "(UTC 05:00) 海地",
  //   "value": "Haiti Standard Time",
  //   "utcOffset": "-05:00",
  //   "timezoneName": "Etc/GMT+5",
  // },
  // {
  //   "name": "(UTC-05:00) Havana",
  //   "nameCn": "(UTC-05:00) 哈瓦那",
  //   "value": "Cuba Standard Time",
  //   "utcOffset": "-05:00",
  //   "timezoneName": "Etc/GMT+5",
  // },
  // {
  //   "name": "(UTC-05:00) Indiana (East)",
  //   "nameCn": "(UTC-05:00) 印地安那(东部)",
  //   "value": "US Eastern Standard Time",
  //   "utcOffset": "-05:00",
  //   "timezoneName": "Etc/GMT+5",
  // },
  // {
  //   "name": "(UTC-05:00) Turks and Caicos",
  //   "nameCn": "(UTC-05:00) 特克斯和凯科斯群岛",
  //   "value": "Turks And Caicos Standard Time",
  //   "utcOffset": "-05:00",
  //   "timezoneName": "Etc/GMT+5",
  // },
  // {
  //   "name": "(UTC-04:00) Caracas",
  //   "nameCn": "(UTC-04:00) 加拉加斯",
  //   "value": "Venezuela Standard Time",
  //   "utcOffset": "-04:00",
  //   "timezoneName": "Etc/GMT+4",
  // },
  // {
  //   "name": "(UTC-03:00) Punta Arenas",
  //   "nameCn": "(UTC 03:00) 蓬塔阿雷纳斯",
  //   "value": "Magallanes Standard Time",
  //   "utcOffset": "-03:00",
  //   "timezoneName": "Etc/GMT+3",
  // },
  // {
  //   "name": "(UTC-04:00) Asuncion",
  //   "nameCn": "(UTC-04:00) 亚松森",
  //   "value": "Paraguay Standard Time",
  //   "utcOffset": "-04:00",
  //   "timezoneName": "Etc/GMT+4",
  // },
  // {
  //   "name": "(UTC-04:00) Atlantic Time (Canada)",
  //   "nameCn": "(UTC-04:00) 大西洋时间(加拿大)",
  //   "value": "Atlantic Standard Time",
  //   "utcOffset": "-04:00",
  //   "timezoneName": "Etc/GMT+4",
  // },
  // {
  //   "name": "(UTC-04:00) Cuiaba",
  //   "nameCn": "(UTC-04:00) 库亚巴",
  //   "value": "Central Brazilian Standard Time",
  //   "utcOffset": "-04:00",
  //   "timezoneName": "Etc/GMT+4",
  // },
  // {
  //   "name": "(UTC-04:00) Georgetown, La Paz, Manaus, San Juan",
  //   "nameCn": "(UTC-04:00) 乔治敦，拉巴斯，马瑙斯，圣胡安",
  //   "value": "SA Western Standard Time",
  //   "utcOffset": "-04:00",
  //   "timezoneName": "Etc/GMT+4",
  // },
  // {
  //   "name": "(UTC-04:00) Santiago",
  //   "nameCn": "(UTC-04:00) 圣地亚哥",
  //   "value": "Pacific SA Standard Time",
  //   "utcOffset": "-04:00",
  //   "timezoneName": "Etc/GMT+4",
  // },
  // // {
  // //   "name": "(UTC-03:30) Newfoundland",
  // //   "nameCn": "(UTC-03:30) 纽芬兰",
  // //   "value": "Newfoundland Standard Time",
  // //   "utcOffset": "-03:30",
  // //   "timezoneName": "Etc/GMT+3",
  // // },
  // {
  //   "name": "(UTC-03:00) Araguaina",
  //   "nameCn": "(UTC-03:00) 阿拉瓜伊纳",
  //   "value": "Tocantins Standard Time",
  //   "utcOffset": "-03:00",
  //   "timezoneName": "Etc/GMT+3",
  // },
  // {
  //   "name": "(UTC-03:00) Brasilia",
  //   "nameCn": "(UTC-03:00) 巴西利亚",
  //   "value": "E. South America Standard Time",
  //   "utcOffset": "-03:00",
  //   "timezoneName": "Etc/GMT+3",
  // },
  // {
  //   "name": "(UTC-03:00) Cayenne, Fortaleza",
  //   "nameCn": "(UTC-03:00) 卡宴，福塔雷萨",
  //   "value": "SA Eastern Standard Time",
  //   "utcOffset": "-03:00",
  //   "timezoneName": "Etc/GMT+3",
  // },
  // {
  //   "name": "(UTC-03:00) City of Buenos Aires",
  //   "nameCn": "(UTC-03:00) 布宜诺斯艾利斯市",
  //   "value": "Argentina Standard Time",
  //   "utcOffset": "-03:00",
  //   "timezoneName": "Etc/GMT+3",
  // },
  // {
  //   "name": "(UTC-03:00) Greenland",
  //   "nameCn": "(UTC-03:00) 格陵兰",
  //   "value": "Greenland Standard Time",
  //   "utcOffset": "-03:00",
  //   "timezoneName": "Etc/GMT+3",
  // },
  // {
  //   "name": "(UTC-03:00) Montevideo",
  //   "nameCn": "(UTC-03:00) 蒙得维的亚",
  //   "value": "Montevideo Standard Time",
  //   "utcOffset": "-03:00",
  //   "timezoneName": "Etc/GMT+3",
  // },
  // {
  //   "name": "(UTC-03:00) Saint Pierre and Miquelon",
  //   "nameCn": "(UTC-03:00) 圣皮埃尔和密克隆",
  //   "value": "Saint Pierre Standard Time",
  //   "utcOffset": "-03:00",
  //   "timezoneName": "Etc/GMT+3",
  // },
  // {
  //   "name": "(UTC-03:00) Salvador",
  //   "nameCn": "(UTC-03:00) 萨尔瓦多",
  //   "value": "Bahia Standard Time",
  //   "utcOffset": "-03:00",
  //   "timezoneName": "Etc/GMT+3",
  // },
  // {
  //   "name": "(UTC-02:00) Coordinated Universal Time-02",
  //   "nameCn": "(UTC-02:00) 协调世界时-02",
  //   "value": "UTC-02",
  //   "utcOffset": "-02:00",
  //   "timezoneName": "Etc/GMT+2",
  // },
  // {
  //   "name": "(UTC-02:00) Mid-Atlantic",
  //   "nameCn": "(UTC-02:00) 中大西洋 - 旧用",
  //   "value": "Mid-Atlantic Standard Time",
  //   "utcOffset": "-02:00",
  //   "timezoneName": "Etc/GMT+2",
  // },
  // {
  //   "name": "(UTC-01:00) Azores",
  //   "nameCn": "(UTC-01:00) 亚速尔群岛",
  //   "value": "Azores Standard Time",
  //   "utcOffset": "-01:00",
  //   "timezoneName": "Etc/GMT+1",
  // },
  // {
  //   "name": "(UTC-01:00) Cabo Verde Is.",
  //   "nameCn": "(UTC-01:00) 佛得角群岛",
  //   "value": "Cape Verde Standard Time",
  //   "utcOffset": "-01:00",
  //   "timezoneName": "Etc/GMT+1",
  // },
  // {
  //   "name": "(UTC+00:00) Monrovia, Reykjavik",
  //   "nameCn": "(UTC+00:00) 蒙罗维亚，雷克雅未克",
  //   "value": "Greenwich Standard Time",
  //   "utcOffset": "+00:00",
  //   "timezoneName": "Etc/GMT-0",
  // },
  // {
  //   "name": "(UTC+01:00) Casablanca",
  //   "nameCn": "(UTC+01:00) 卡萨布兰卡",
  //   "value": "Morocco Standard Time",
  //   "utcOffset": "+01:00",
  //   "timezoneName": "Etc/GMT-1",
  // },
  // {
  //   "name": "(UTC+01:00) Belgrade, Bratislava, Budapest, Ljubljana, Prague",
  //   "nameCn": "(UTC+01:00) 贝尔格莱德，布拉迪斯拉发，布达佩斯，卢布尔雅那，布拉格",
  //   "value": "Central Europe Standard Time",
  //   "utcOffset": "+01:00",
  //   "timezoneName": "Etc/GMT-1",
  // },
  // {
  //   "name": "(UTC+01:00) Brussels, Copenhagen, Madrid, Paris",
  //   "nameCn": "(UTC+01:00) 布鲁塞尔，哥本哈根，马德里，巴黎",
  //   "value": "Romance Standard Time",
  //   "utcOffset": "+01:00",
  //   "timezoneName": "Etc/GMT-1",
  // },
  // {
  //   "name": "(UTC+01:00) Sarajevo, Skopje, Warsaw, Zagreb",
  //   "nameCn": "(UTC+01:00) 萨拉热窝，斯科普里，华沙，萨格勒布",
  //   "value": "Central European Standard Time",
  //   "utcOffset": "+01:00",
  //   "timezoneName": "Etc/GMT-1",
  // },
  // {
  //   "name": "(UTC+01:00) West Central Africa",
  //   "nameCn": "(UTC+01:00) 中非西部",
  //   "value": "W. Central Africa Standard Time",
  //   "utcOffset": "+01:00",
  //   "timezoneName": "Etc/GMT-1",
  // },
  // {
  //   "name": "(UTC+02:00) Tripoli",
  //   "nameCn": "(UTC+02:00) 的黎波里",
  //   "value": "Libya Standard Time",
  //   "utcOffset": "+02:00",
  //   "timezoneName": "Etc/GMT-2",
  // },
  // {
  //   "name": "(UTC+02:00) Windhoek",
  //   "nameCn": "(UTC+02:00) 温得和克",
  //   "value": "Namibia Standard Time",
  //   "utcOffset": "+02:00",
  //   "timezoneName": "Etc/GMT-2",
  // },
  // {
  //   "name": "(UTC+02:00) Amman",
  //   "nameCn": "(UTC+02:00) 安曼",
  //   "value": "Jordan Standard Time",
  //   "utcOffset": "+02:00",
  //   "timezoneName": "Etc/GMT-2",
  // },
  // {
  //   "name": "(UTC+02:00) Athens, Bucharest",
  //   "nameCn": "(UTC+02:00) 雅典，布加勒斯特",
  //   "value": "GTB Standard Time",
  //   "utcOffset": "+02:00",
  //   "timezoneName": "Etc/GMT-2",
  // },
  // {
  //   "name": "(UTC+02:00) Beirut",
  //   "nameCn": "(UTC+02:00) 贝鲁特",
  //   "value": "Middle East Standard Time",
  //   "utcOffset": "+02:00",
  //   "timezoneName": "Etc/GMT-2",
  // },
  // {
  //   "name": "(UTC+02:00) Cairo",
  //   "nameCn": "(UTC+02:00) 开罗",
  //   "value": "Egypt Standard Time",
  //   "utcOffset": "+02:00",
  //   "timezoneName": "Etc/GMT-2",
  // },
  // {
  //   "name": "(UTC+02:00) Chisinau",
  //   "nameCn": "(UTC+02:00) 基希纳乌",
  //   "value": "E. Europe Standard Time",
  //   "utcOffset": "+02:00",
  //   "timezoneName": "Etc/GMT-2",
  // },
  // {
  //   "name": "(UTC+02:00) Damascus",
  //   "nameCn": "(UTC+02:00) 大马士革",
  //   "value": "Syria Standard Time",
  //   "utcOffset": "+02:00",
  //   "timezoneName": "Etc/GMT-2",
  // },
  // {
  //   "name": "(UTC+02:00) Gaza, Hebron",
  //   "nameCn": "(UTC+02:00) 加沙，希伯伦",
  //   "value": "West Bank Standard Time",
  //   "utcOffset": "+02:00",
  //   "timezoneName": "Etc/GMT-2",
  // },
  // {
  //   "name": "(UTC+02:00) Harare, Pretoria",
  //   "nameCn": "(UTC+02:00) 哈拉雷，比勒陀利亚",
  //   "value": "South Africa Standard Time",
  //   "utcOffset": "+02:00",
  //   "timezoneName": "Etc/GMT-2",
  // },
  // {
  //   "name": "(UTC+02:00) Helsinki, Kyiv, Riga, Sofia, Tallinn, Vilnius",
  //   "nameCn": "(UTC+02:00) 赫尔辛基，基辅，里加，索非亚，塔林，维尔纽斯",
  //   "value": "FLE Standard Time",
  //   "utcOffset": "+02:00",
  //   "timezoneName": "Etc/GMT-2",
  // },
  // {
  //   "name": "(UTC+02:00) Jerusalem",
  //   "nameCn": "(UTC+02:00) 耶路撒冷",
  //   "value": "Israel Standard Time",
  //   "utcOffset": "+02:00",
  //   "timezoneName": "Etc/GMT-2",
  // },
  // {
  //   "name": "(UTC+02:00) Kaliningrad",
  //   "nameCn": "(UTC+02:00) 加里宁格勒",
  //   "value": "Kaliningrad Standard Time",
  //   "utcOffset": "+02:00",
  //   "timezoneName": "Etc/GMT-2",
  // },
  // {
  //   "name": "(UTC+02:00) Khartoum",
  //   "nameCn": "(UTC+02:00) 喀土木",
  //   "value": "Sudan Standard Time",
  //   "utcOffset": "+02:00",
  //   "timezoneName": "Etc/GMT-2",
  // },
  // {
  //   "name": "(UTC+03:00) Istanbul",
  //   "nameCn": "(UTC+03:00) 伊斯坦布尔",
  //   "value": "Turkey Standard Time",
  //   "utcOffset": "+03:00",
  //   "timezoneName": "Etc/GMT-3",
  // },
  // {
  //   "name": "(UTC+03:00) Minsk",
  //   "nameCn": "(UTC+03:00) 明斯克",
  //   "value": "Belarus Standard Time",
  //   "utcOffset": "+03:00",
  //   "timezoneName": "Etc/GMT-3",
  // },
  // {
  //   "name": "(UTC+03:00) Baghdad",
  //   "nameCn": "(UTC+03:00) 巴格达",
  //   "value": "Arabic Standard Time",
  //   "utcOffset": "+03:00",
  //   "timezoneName": "Etc/GMT-3",
  // },
  // {
  //   "name": "(UTC+03:00) Kuwait, Riyadh",
  //   "nameCn": "(UTC+03:00) 科威特，利雅得",
  //   "value": "Arab Standard Time",
  //   "utcOffset": "+03:00",
  //   "timezoneName": "Etc/GMT-3",
  // },
  // {
  //   "name": "(UTC+03:00) Moscow, St. Petersburg",
  //   "nameCn": "(UTC+03:00) 莫斯科、圣彼德斯堡",
  //   "value": "Russian Standard Time",
  //   "utcOffset": "+03:00",
  //   "timezoneName": "Etc/GMT-3",
  // },
  // {
  //   "name": "(UTC+03:00) Nairobi",
  //   "nameCn": "(UTC+03:00) 内罗毕",
  //   "value": "E. Africa Standard Time",
  //   "utcOffset": "+03:00",
  //   "timezoneName": "Etc/GMT-3",
  // },
  // {
  //   "name": "(UTC+04:00) Astrakhan, Ulyanovsk",
  //   "nameCn": "(UTC+04:00) 阿斯特拉罕，乌里扬诺夫斯克",
  //   "value": "Astrakhan Standard Time",
  //   "utcOffset": "+04:00",
  //   "timezoneName": "Etc/GMT-4",
  // },
  // {
  //   "name": "(UTC+04:00) Izhevsk, Samara",
  //   "nameCn": "(UTC+04:00) 伊热夫斯克，萨马拉",
  //   "value": "Russia Time Zone 3",
  //   "utcOffset": "+04:00",
  //   "timezoneName": "Etc/GMT-4",
  // },
  // {
  //   "name": "(UTC+04:00) Saratov",
  //   "nameCn": "(UTC+04:00) 萨拉托夫",
  //   "value": "Saratov Standard Time",
  //   "utcOffset": "+04:00",
  //   "timezoneName": "Etc/GMT-4",
  // },
  // {
  //   "name": "(UTC+04:00) Volgograd",
  //   "nameCn": "(UTC+04:00) 伏尔加格勒",
  //   "value": "Volgograd Standard Time",
  //   "utcOffset": "+04:00",
  //   "timezoneName": "Etc/GMT-4",
  // },
  // // {
  // //   "name": "(UTC+03:30) Tehran",
  // //   "nameCn": "(UTC+03:30) 德黑兰",
  // //   "value": "Iran Standard Time",
  // //   "utcOffset": "+03:30",
  // //   "timezoneName": "Etc/GMT-3",
  // // },
  // {
  //   "name": "(UTC+04:00) Abu Dhabi, Muscat",
  //   "nameCn": "(UTC+04:00) 阿尔扎比，马斯喀特",
  //   "value": "Arabian Standard Time",
  //   "utcOffset": "+04:00",
  //   "timezoneName": "Etc/GMT-4",
  // },
  // {
  //   "name": "(UTC+04:00) Baku",
  //   "nameCn": "(UTC+04:00) 巴库",
  //   "value": "Azerbaijan Standard Time",
  //   "utcOffset": "+04:00",
  //   "timezoneName": "Etc/GMT-4",
  // },
  // {
  //   "name": "(UTC+04:00) Port Louis",
  //   "nameCn": "(UTC+04:00) 路易港",
  //   "value": "Mauritius Standard Time",
  //   "utcOffset": "+04:00",
  //   "timezoneName": "Etc/GMT-4",
  // },
  // {
  //   "name": "(UTC+04:00) Tbilisi",
  //   "nameCn": "(UTC+04:00) 第比利斯",
  //   "value": "Georgian Standard Time",
  //   "utcOffset": "+04:00",
  //   "timezoneName": "Etc/GMT-4",
  // },
  // {
  //   "name": "(UTC+04:00) Yerevan",
  //   "nameCn": "(UTC+04:00) 埃里温",
  //   "value": "Caucasus Standard Time",
  //   "utcOffset": "+04:00",
  //   "timezoneName": "Etc/GMT-4",
  // },
  // // {
  // //   "name": "(UTC+04:30) Kabul",
  // //   "nameCn": "(UTC+04:30) 喀布尔",
  // //   "value": "Afghanistan Standard Time",
  // //   "utcOffset": "+04:30",
  // //   "timezoneName": "Etc/GMT-4",
  // // },
  // {
  //   "name": "(UTC+05:00) Ashgabat, Toshkent",
  //   "nameCn": "(UTC+05:00) 阿什哈巴德，塔什干",
  //   "value": "West Asia Standard Time",
  //   "utcOffset": "+05:00",
  //   "timezoneName": "Etc/GMT-5",
  // },
  // {
  //   "name": "(UTC+05:00) Ekaterinburg",
  //   "nameCn": "(UTC + 05:00) 叶卡特琳堡",
  //   "value": "Ekaterinburg Standard Time",
  //   "utcOffset": "+05:00",
  //   "timezoneName": "Etc/GMT-5",
  // },
  // {
  //   "name": "(UTC+05:00) Islamabad, Karachi",
  //   "nameCn": "(UTC+05:00) 伊斯兰堡，卡拉奇",
  //   "value": "Pakistan Standard Time",
  //   "utcOffset": "+05:00",
  //   "timezoneName": "Etc/GMT-5",
  // },
  // {
  //   "name": "(UTC+05:00) Qyzylorda",
  //   "nameCn": "(UTC+05:00) 克孜勒奥尔达",
  //   "value": "Qyzylorda Standard Time",
  //   "utcOffset": "+05:00",
  //   "timezoneName": "Etc/GMT-5",
  // },
  // // {
  // //   "name": "(UTC+05:30) Sri Jayawardenepura",
  // //   "nameCn": "(UTC+05:30) 斯里加亚渥登普拉",
  // //   "value": "Sri Lanka Standard Time",
  // //   "utcOffset": "+05:30",
  // //   "timezoneName": "Etc/GMT-5",
  // // },
  // // {
  // //   "name": "(UTC+05:45) Kathmandu",
  // //   "nameCn": "(UTC+05:45) 加德满都",
  // //   "value": "Nepal Standard Time",
  // //   "utcOffset": "+05:45",
  // //   "timezoneName": "Etc/GMT-5",
  // // },
  // {
  //   "name": "(UTC+06:00) Astana",
  //   "nameCn": "(UTC+06:00) 阿斯塔纳",
  //   "value": "Central Asia Standard Time",
  //   "utcOffset": "+06:00",
  //   "timezoneName": "Etc/GMT-6",
  // },
  // {
  //   "name": "(UTC+06:00) Dhaka",
  //   "nameCn": "(UTC+06:00) 达卡",
  //   "value": "Bangladesh Standard Time",
  //   "utcOffset": "+06:00",
  //   "timezoneName": "Etc/GMT-6",
  // },
  // {
  //   "name": "(UTC+06:00) Omsk",
  //   "nameCn": "(UTC+06:00) 鄂木斯克",
  //   "value": "Omsk Standard Time",
  //   "utcOffset": "+06:00",
  //   "timezoneName": "Etc/GMT-6",
  // },
  // {
  //   "name": "(UTC+07:00) Barnaul, Gorno-Altaysk",
  //   "nameCn": "(UTC+07:00) 巴尔瑙尔，戈尔诺-阿尔泰斯克",
  //   "value": "Altai Standard Time",
  //   "utcOffset": "+07:00",
  //   "timezoneName": "Etc/GMT-7",
  // },
  // {
  //   "name": "(UTC+07:00) Novosibirsk",
  //   "nameCn": "(UTC+07:00) 新西伯利亚",
  //   "value": "N. Central Asia Standard Time",
  //   "utcOffset": "+07:00",
  //   "timezoneName": "Etc/GMT-7",
  // },
  // {
  //   "name": "(UTC+07:00) Tomsk",
  //   "nameCn": "(UTC+07:00) 托木斯克",
  //   "value": "Tomsk Standard Time",
  //   "utcOffset": "+07:00",
  //   "timezoneName": "Etc/GMT-7",
  // },
  // // {
  // //   "name": "(UTC+06:30) Yangon (Rangoon)",
  // //   "nameCn": "(UTC+06:30) 仰光",
  // //   "value": "Myanmar Standard Time",
  // //   "utcOffset": "+06:30",
  // //   "timezoneName": "Etc/GMT-6",
  // // },
  // {
  //   "name": "(UTC+07:00) Bangkok, Hanoi, Jakarta",
  //   "nameCn": "(UTC+07:00) 曼谷，河内，雅加达",
  //   "value": "SE Asia Standard Time",
  //   "utcOffset": "+07:00",
  //   "timezoneName": "Etc/GMT-7",
  // },
  // {
  //   "name": "(UTC+07:00) Hovd",
  //   "nameCn": "(UTC+07:00) 科布多",
  //   "value": "W. Mongolia Standard Time",
  //   "utcOffset": "+07:00",
  //   "timezoneName": "Etc/GMT-7",
  // },
  // {
  //   "name": "(UTC+07:00) Krasnoyarsk",
  //   "nameCn": "(UTC+07:00) 克拉斯诺亚尔斯克",
  //   "value": "North Asia Standard Time",
  //   "utcOffset": "+07:00",
  //   "timezoneName": "Etc/GMT-7",
  // },
  // {
  //   "name": "(UTC+08:00) Irkutsk",
  //   "nameCn": "(UTC+08:00) 伊尔库茨克",
  //   "value": "North Asia East Standard Time",
  //   "utcOffset": "+08:00",
  //   "timezoneName": "Etc/GMT-8",
  // },
  // {
  //   "name": "(UTC+08:00) Kuala Lumpur, Singapore",
  //   "nameCn": "(UTC+08:00) 吉隆坡，新加坡",
  //   "value": "Singapore Standard Time",
  //   "utcOffset": "+08:00",
  //   "timezoneName": "Etc/GMT-8",
  // },
  // {
  //   "name": "(UTC+08:00) Perth",
  //   "nameCn": "(UTC+08:00) 珀斯",
  //   "value": "W. Australia Standard Time",
  //   "utcOffset": "+08:00",
  //   "timezoneName": "Etc/GMT-8",
  // },
  // {
  //   "name": "(UTC+08:00) Taipei",
  //   "nameCn": "(UTC+08:00) 台北",
  //   "value": "Taipei Standard Time",
  //   "utcOffset": "+08:00",
  //   "timezoneName": "Etc/GMT-8",
  // },
  // {
  //   "name": "(UTC+08:00) Ulaanbaatar",
  //   "nameCn": "(UTC+08:00) 乌兰巴托",
  //   "value": "Ulaanbaatar Standard Time",
  //   "utcOffset": "+08:00",
  //   "timezoneName": "Etc/GMT-8",
  // },
  // {
  //   "name": "(UTC+09:00) Chita",
  //   "nameCn": "(UTC+09:00) 赤塔",
  //   "value": "Transbaikal Standard Time",
  //   "utcOffset": "+09:00",
  //   "timezoneName": "Etc/GMT-9",
  // },
  // {
  //   "name": "(UTC+09:00) Pyongyang",
  //   "nameCn": "(UTC+09:00) 平壤",
  //   "value": "North Korea Standard Time",
  //   "utcOffset": "+09:00",
  //   "timezoneName": "Etc/GMT-9",
  // },
  // // {
  // //   "name": "(UTC+08:45) Eucla",
  // //   "nameCn": "(UTC+08:45) 尤克拉",
  // //   "value": "Aus Central W. Standard Time",
  // //   "utcOffset": "+08:45",
  // //   "timezoneName": "Etc/GMT-8",
  // // },
  // {
  //   "name": "(UTC+09:00) Seoul",
  //   "nameCn": "(UTC+09:00) 首尔",
  //   "value": "Korea Standard Time",
  //   "utcOffset": "+09:00",
  //   "timezoneName": "Etc/GMT-9",
  // },
  // {
  //   "name": "(UTC+09:00) Yakutsk",
  //   "nameCn": "(UTC+09:00) 雅库茨克",
  //   "value": "Yakutsk Standard Time",
  //   "utcOffset": "+09:00",
  //   "timezoneName": "Etc/GMT-9",
  // },
  // // {
  // //   "name": "(UTC+09:30) Adelaide",
  // //   "nameCn": "(UTC+09:30) 阿德莱德",
  // //   "value": "Cen. Australia Standard Time",
  // //   "utcOffset": "+09:30",
  // //   "timezoneName": "Etc/GMT-9",
  // // },
  // // {
  // //   "name": "(UTC+09:30) Darwin",
  // //   "nameCn": "(UTC+09:30) 达尔文",
  // //   "value": "AUS Central Standard Time",
  // //   "utcOffset": "+09:30",
  // //   "timezoneName": "Etc/GMT-9",
  // // },
  // {
  //   "name": "(UTC+10:00) Brisbane",
  //   "nameCn": "(UTC+10:00) 布里斯班",
  //   "value": "E. Australia Standard Time",
  //   "utcOffset": "+10:00",
  //   "timezoneName": "Etc/GMT-10",
  // },
  // {
  //   "name": "(UTC+10:00) Guam, Port Moresby",
  //   "nameCn": "(UTC+10:00) 关岛，莫尔兹比港",
  //   "value": "West Pacific Standard Time",
  //   "utcOffset": "+10:00",
  //   "timezoneName": "Etc/GMT-10",
  // },
  // {
  //   "name": "(UTC+10:00) Hobart",
  //   "nameCn": "(UTC+10:00) 霍巴特",
  //   "value": "Tasmania Standard Time",
  //   "utcOffset": "+10:00",
  //   "timezoneName": "Etc/GMT-10",
  // },
  // {
  //   "name": "(UTC+10:00) Vladivostok",
  //   "nameCn": "(UTC+10:00) 海参崴",
  //   "value": "Vladivostok Standard Time",
  //   "utcOffset": "+10:00",
  //   "timezoneName": "Etc/GMT-10",
  // },
  // {
  //   "name": "(UTC+11:00) Bougainville Island",
  //   "nameCn": "(UTC+11:00) 布干维尔岛",
  //   "value": "Bougainville Standard Time",
  //   "utcOffset": "+11:00",
  //   "timezoneName": "Etc/GMT-11",
  // },
  // {
  //   "name": "(UTC+11:00) Magadan",
  //   "nameCn": "(UTC+11:00) 马加丹",
  //   "value": "Magadan Standard Time",
  //   "utcOffset": "+11:00",
  //   "timezoneName": "Etc/GMT-11",
  // },
  // {
  //   "name": "(UTC+11:00) Sakhalin",
  //   "nameCn": "(UTC+11:00) 萨哈林",
  //   "value": "Sakhalin Standard Time",
  //   "utcOffset": "+11:00",
  //   "timezoneName": "Etc/GMT-11",
  // },
  // // {
  // //   "name": "(UTC+10:30) Lord Howe Island",
  // //   "nameCn": "(UTC+10:30) 豪勋爵岛",
  // //   "value": "Lord Howe Standard Time",
  // //   "utcOffset": "+10:30",
  // //   "timezoneName": "Etc/GMT-10",
  // // },
  // {
  //   "name": "(UTC+11:00) Chokurdakh",
  //   "nameCn": "(UTC+11:00) 乔库尔达赫",
  //   "value": "Russia Time Zone 10",
  //   "utcOffset": "+11:00",
  //   "timezoneName": "Etc/GMT-11",
  // },
  // {
  //   "name": "(UTC+11:00) Norfolk Island",
  //   "nameCn": "(UTC+11:00) 诺福克岛",
  //   "value": "Norfolk Standard Time",
  //   "utcOffset": "+11:00",
  //   "timezoneName": "Etc/GMT-11",
  // },
  // {
  //   "name": "(UTC+11:00) Solomon Is., New Caledonia",
  //   "nameCn": "(UTC+11:00) 所罗门群岛，新喀里多尼亚",
  //   "value": "Central Pacific Standard Time",
  //   "utcOffset": "+11:00",
  //   "timezoneName": "Etc/GMT-11",
  // },
  // {
  //   "name": "(UTC+12:00) Anadyr, Petropavlovsk-Kamchatsky",
  //   "nameCn": "(UTC+12:00) 阿纳德尔，勘察加彼得巴甫洛夫斯克",
  //   "value": "Russia Time Zone 11",
  //   "utcOffset": "+12:00",
  //   "timezoneName": "Etc/GMT-12",
  // },
  // {
  //   "name": "(UTC+12:00) Auckland, Wellington",
  //   "nameCn": "(UTC+12:00) 奥克兰，惠灵顿",
  //   "value": "New Zealand Standard Time",
  //   "utcOffset": "+12:00",
  //   "timezoneName": "Etc/GMT-12",
  // },
  // {
  //   "name": "(UTC+12:00) Coordinated Universal Time+12",
  //   "nameCn": "(UTC+12:00) 协调世界时+12",
  //   "value": "UTC+12",
  //   "utcOffset": "+12:00",
  //   "timezoneName": "Etc/GMT-12",
  // },
  // {
  //   "name": "(UTC+12:00) Fiji",
  //   "nameCn": "(UTC+12:00) 斐济",
  //   "value": "Fiji Standard Time",
  //   "utcOffset": "+12:00",
  //   "timezoneName": "Etc/GMT-12",
  // },
  // {
  //   "name": "(UTC+12:00) Petropavlovsk-Kamchatsky - Old",
  //   "nameCn": "(UTC+12:00) 堪察加彼得罗巴甫洛夫斯克 - 旧用",
  //   "value": "Kamchatka Standard Time",
  //   "utcOffset": "+12:00",
  //   "timezoneName": "Etc/GMT-12",
  // },
  // // {
  // //   "name": "(UTC+12:45) Chatham Islands",
  // //   "nameCn": "(UTC+12:45) 查塔姆群岛",
  // //   "value": "Chatham Islands Standard Time",
  // //   "utcOffset": "+12:45",
  // //   "timezoneName": "Etc/GMT-12",
  // // },
  // {
  //   "name": "(UTC+13:00) Coordinated Universal Time+13",
  //   "nameCn": "(UTC+13:00) 协调世界时+13",
  //   "value": "UTC+13",
  //   "utcOffset": "+13:00",
  //   "timezoneName": "Etc/GMT-13",
  // },
  // {
  //   "name": "(UTC+13:00) Nuku'alofa",
  //   "nameCn": "(UTC+13:00) 努库阿洛法",
  //   "value": "Tonga Standard Time",
  //   "utcOffset": "+13:00",
  //   "timezoneName": "Etc/GMT-13",
  // },
  // {
  //   "name": "(UTC+14:00) Kiritimati Island",
  //   "nameCn": "(UTC+14:00) 圣诞",
  //   "value": "Line Islands Standard Time",
  //   "utcOffset": "+14:00",
  //   "timezoneName": "Etc/GMT-14",
  // }
];

export const allowTimezoneNameStrs = timezoneNames.map(v=>v.timezoneName);
